### ISSUE TITLE
Forge Launcher Fails To Find New Versions

### ISSUE THREAD

**Issue by Shaggy01** [churrufli/forgelauncher#1]
When opening, forge launcher can't detect new snapshots. Forge recently updated their launcher to "Forge V2" so an update is requested, thanks! I love this program <3

**Comment by churrufli** [comment]
Hi, I have updated the program. Check from Forge Launcher > Check Forge Launcher updates if you update it to the new version (2.1.24). With the new version, could you check if it updates Forge correctly? thank you

**Comment by onura46** [comment]
Seems to be functional for me!

**Comment by churrufli** [comment]
Solved!
