### ISSUE TITLE
Latest update is flagged a malicous by numerous security programs

### ISSUE THREAD

**Issue by Eiim** [churrufli/forgelauncher#3]
This VirusTotal analysis of the most recent published exe has 14 vendors indicating that it may be malicous, including Microsoft's built-in Windows Security:

https://www.virustotal.com/gui/file/cec35c2cdaa7c38194bc94f1cfccc9eabf5496e1ddaa33d0b2bdc2f75bbe529c/detection

**Comment by churrufli** [comment]
Thank you very much information, I don't understand why it is happening now
and I will have to see what the reason is. Feel free to check the code or
compile by yourself.

**Comment by churrufli** [comment]
@Eiim could you try the latest compiled version? I have re-referenced the icon and some more changes. Do you have any idea why this is happening? Thanks https://github.com/churrufli/forgelauncher/releases/tag/v2.1.7

**Comment by Eiim** [comment]
I re-downloaded and re-analyzed and there doesn't seem to be any improvement: https://www.virustotal.com/gui/file/f9fc57c441032012fd50ef14f69bbb61b566049a0fda4639601f8814b0839c6f/detection

I'm not sure what the reason for this is. I can try to build the version on the cleaning branch and see if it passes.

**Comment by Eiim** [comment]
I tried to build the cleaning branch, but couldn't. There seems to be an issue with FxCop, which is [deprecated](https://docs.microsoft.com/en-us/visualstudio/code-quality/migrate-from-legacy-analysis-to-net-analyzers?view=vs-2019).

Error:
```
The specified task executable "FxCopCmd.exe" could not be run. System.ComponentModel.Win32Exception (0x80004005): The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.Build.Utilities.ToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands)
   at Microsoft.Build.Utilities.ToolTask.Execute()
```

**Comment by churrufli** [comment]
@Eiim pls, may you check last compiled .exe? I have made some changes in the compilation configuration to remove the code analysis, it was a default option enabled in the project in Visual Studio. Branch cleaning is up to date. thanks in advance

**Comment by deusversus** [comment]
Forge Launcher is being flagged by Windows Defender, making it VERY hard to use the program. Will this be fixed in the foreseeable future?

**Comment by churrufli** [comment]
user in discord says "Just got a virus warning from the Launcher."

**Comment by maforget** [comment]
Don't know really I had the same problem already. It's sometimes good when used locally (checking with virustotal), but when it starts being opened on other computer the cloud protection of windows defender decides that it has a low reputation (not enough people using it) and flags it has suspicious. What you can do is submitted to MS has a false positive https://www.microsoft.com/en-us/wdsi/filesubmission. 

I had to do it for 1 of my project https://github.com/maforget/ComicRackKeygen. I had to submit it (as a dev) twice with a link to the source code and it's now ok. But a lot of other AV still gets it flagged, but in my case it's seen as a HackTool, which isn't as scary and with the name Keygen in it, it's kind of understandable. I didn't bother contacting other AV's.

I believe that signing your file may help being seen as suspicious. I don't know if a self-signed would be ok or you would need to get a certificate.

**Comment by churrufli** [comment]
Following the indications you gave me, it seems that MS has stopped detecting it, good news. Thanks!
